[networking]
backend_address = "localhost"
backend_port = "3365"

[networking.experimental]
max_network_listeners = 1 # This option sets the maximum number of connections between the backend and GUI, allowing multiple GUIs to exist. It is highly experimental and not guaranteed to work, as creating additional listeners is not currently supported. The minimum value is 1 and the maximum is 10.